version: "3"

services:

  anaconda_jupyter_notebook:
    image: continuumio/anaconda3
    container_name: ${PROJECT_NAME}
    ports:
      - "${PORT}:8888"
    volumes:
      - ../app/:/opt/notebooks
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices : 
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    privileged: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


    environment:
      - DISPLAY=unix$DISPLAY
    command: >
      bash -c "
        mkdir -p /opt/notebooks &&
        jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root 
      "